language: php
dist: xenial

services:
  - mysql

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"

php:
  - 7.3

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"

matrix:
  allow_failures:
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~8.8.0
  include:
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~8.7.0
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~8.7.0
      php: 7.2
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~8.8.0 DRUPAL_TESTING_TEST_DEPRECATION=false
      php: 7.2
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~8.8.0
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~8.8.0 DRUPAL_TESTING_TEST_DEPRECATION=false

before_install:
  - composer global require thunder/drupal-testing

before_script:
  - phpenv config-rm xdebug.ini

script:
  - test-drupal-project

notifications:
  email: false
